name: test
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14.17.5

      - name: Install Server dependencies
        working-directory: ./server
        run: |
          npm install

      - name: Run unit Server tests
        working-directory: ./server
        run: |
          CI=true npm run test:coverage

      - name: Install UI dependencies
        working-directory: ./ui
        run: |
          npm install

      - name: Run UI tests
        working-directory: ./ui
        run: |
          CI=true npm test -- --coverage -u